### ISSUE TITLE
which five scenes from  scannet++ are used in paper benchmark?

### ISSUE THREAD

**Issue by jason718** [barbararoessle/ganerf#2]
Can you share the id? So that the numbers can be fairly compared.

**Comment by barbararoessle** [comment]
Hi, the following 5 scenes were used: 2e74812d00, 98b4ec142f, ab6983ae6c, 84b48f2614, 4ef75031e3. Unfortunately, in the dataset release, scenes 84b48f2614 & 4ef75031e3 are part of the test set, so test images are not available.

**Comment by Jahurto** [comment]
Hi, since the test images for the scenes 84b48f2614 and 4ef75031e3 are not available, how did you obtain evaluation data for these two scenes? How can we compare with your method on these two scenes?
